apiVersion: v1 
kind: PersisitentVolume 
metadata: 
       name: ebs-static 
spec:  
    accessMOdes: 
    - ReadWriteOnce 
    capacity:
       storage: 20Gi 
    csi: 
      driver: ebs.csi.aws.com 
      fsType: ext4 
      volumeHandle:                             
--- 

apiVersion:  v1 
kind: PersistantVolumeClaim 
metadata: 
      name: ebs-static 
spec: 
   StrorageClassName: # empty string must be explicty set otherwise default storageclass will be set 
   volumeName: ebs-static 
   accessModes: 
   - ReadWriteOnce 
   resources:
      requests: 
        storage: 15Gi 
--- 

apiVersion: v1 
kind: Pod 
metadata: 
      name: nginx 
      labels: 
         purpose: ebs-static-demo 
         project: roboshop 
spec: 
   nodeSelector: 
     topology.kubernetes.io/zone:us-east-1b 
   containers: 
   - name: nginx 
     image: nginx 
     volumeMounts: 
     - name: persistant-storage 
       mountpath: /usr/share/nginx/html 
   volumes: 
   - name: persistant-storage 
     persistantVolumeClaim: 
        name: ebs-static 
--- 

apiVersion: v1 
kind: Srvice 
metadata: 
      name: ebs-static 
      labels: 
         purpose: ebs-static-demo 
         project: roboshop 
spec: 
   type: LoadBalancer 
   selector: 
      purpose: ebs-static-demo 
      project: roboshop 
   ports: 
   - protocol:  TCP 
     port: 80 # service port
     targetPort: 80 # containerPort 