apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata: 
    name: efs-storage 
provisioner: efs.csi.aws.com 
reclaimPolicy: Retain 
parameters: 
     provisioningMode: efs-ap 
     FileSystemId: fs-02ed08f5f019fac6f
     directoryPerms: "700"
     basePath: "/roboshop" #/roboshop/cart