apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata: 
    name: efs-storage 
provisioner: efs.csi.aws.com 
reClaimPoilicy: Retain 
parameters: 
     provisioningMode: efs-ap 
     fileSystemId: 
     directoryPerms: 700 
     basePath: "/roboshop" #/roboshop/cart/