apiVersion: v1 
kind: PersisitentVolumeClaim 
metadata: 
      name: efs-dynamic 
spec: 
    accessModes: 
    - ReadWriteOnce 
    storageClassName: "efs-storage" 
    reources: 
         requests: 
            storage: 4Gi 
--- 
apiVersion: v1 
kind: Pod 
metadata: 
       name: nginx 
       labels: 
          purpose: efs-dynamic-demo 
          project: roboshop 
spec: 
   nodeSelector: 
      topology.kubernetes.io/zone: us-east-1b 
   containers: 
   - name: nginx 
     image: nginx 
     volumeMounts: 
     - name: persistent-storage 
       mountPath: /usr/share/nginx/html 
   volumes: 
   - name: persiitent-stoarge 
     persistentVolumeClaim:
          name: efs-dynamic 
--- 
apiVersion: v1 
kind: Service 
metadata:
      name: efs-dynamic 
      labels: 
         purpose: efs-dynamic-demo 
         project: roboshop 
spec: 
   selector: 
      purpose: efs-dynammic-demo 
      project: roboshop 
   ports: 
   - protocol: TCP 
     port: 80 # service port 
     targetPort: 80 # container port                                                       