apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
    name: efs-dynamic 
spec:
   storageClassName: "efs-roboshop" 
   accessModes:
   - ReadWriteOnce 
   resources: 
      requests:
         storage: 5Gi
--- 
apiVersion: v1 
kind: Pod 
metadata: 
     name: nginx  
     labels: 
        purpose: efs-dynamic-demo 
        project: roboshop 
spec: 
   nodeSelector: 
      topology.kubernetes.io/zone: us-east-1d 
   containers: 
   - name: nginx 
     image: nginx:latest  
     volumeMounts: 
     - name: persistent-storage 
       mountPath: /usr/share/nginx/html 
   volumes: 
   - name: persistent-storage 
     persistentVolumeClaim: 
        claimName: efs-dynamic 
--- 
apiVersion: v1 
kind: Service  
metadata: 
    name: efs-dynamic 
    labels: 
       purpose: efs-dynamic-demo 
       project: roboshop 
spec: 
  type: LoadBalancer 
  selector: 
     purpose: efs-dynamic-demo 
     project: roboshop 
  ports:
  - protocol: TCP 
    port: 80 #service port 
    targetPort: 80 #container port                                            
