apiVersion: v1 
kind: Pod 
metadata: 
     name: envars-demo 
     labels: 
        name: demonstrate-demo 
spec: 
   containers: 
   - name: nginx 
     image: nginx 
     env: 
     - name: COURSE 
       value: "KUBERNETES"
     - name: TRAINER 
       value: "SIVAKUMR REDDY M"              