apiVersion: v1 
kind: ReplicaSet 
metadata: 
    name: nginx 
    #replicaset labels 
    labels: 
       purpose: rs-demo 
       project: roboshop 
       app: nginx 
spec: 
   replicas: 2 
   # these are the labels replicaset , use to create pod replicas , this should match to pod labels 
   selector: 
      purpose: rs-demo 
      project: roboshop 
      app: nginx 

   # This is pod definition 
   template: 
      metadata: 
         purpose: rs-demo 
         project: roboshop 
         app: nginx 
      spec: 
         containers: 
         - name: nginx 
           image: nginx                     