apiVersion: v1 
kind: Pod 
metadata:
     labels: 
        test: liveness 
        name: liveness-http 
spec: 
    containers: 
    - name: liveness 
      image: nginx  
      liveness_probe: 
         topSocket: 
            port: 80 
         initialDelayedSeconds: 30 
         periodSeconds: 10
      readiness_probe: 
         httpGet:
            path: /
            port: 80 
         initialDelayedSeconds: 40 
         periodSeconds: 3 
                          
                                  